<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="decode_significant_figures_tests.TestDecodeSignificantFiguresTests-20181018212909" skipped="0" tests="2" time="0.001" timestamp="2018-10-18T21:29:09">
	<testcase classname="decode_significant_figures_tests.TestDecodeSignificantFiguresTests" name="testDecodeSignificantFiguresWhenFourBandsWithBlackInBothBands" time="0.000" timestamp="2018-10-18T21:29:09"/>
	<testcase classname="decode_significant_figures_tests.TestDecodeSignificantFiguresTests" name="testDecodeSignificantFiguresWhenFiveBandsWithBlackInThreeBands" time="0.001" timestamp="2018-10-18T21:29:09">
		<failure message="-1 != 0" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/Users/ras/Projects/Python/cs3280/project2/src/unittest/python/decode_significant_figures_tests.py", line 13, in testDecodeSignificantFiguresWhenFiveBandsWithBlackInThreeBands
    self.assertEquals(decodeSignificantFigures(colors), 0)
AssertionError: -1 != 0
]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
