<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="decode_significant_figures_tests.TestDecodeSignificantFiguresTests-20181018213827" skipped="0" tests="6" time="0.001" timestamp="2018-10-18T21:38:27">
	<testcase classname="decode_significant_figures_tests.TestDecodeSignificantFiguresTests" name="testDecodeSigFigWhenFiveBandsWithBlackBlackBlack" time="0.000" timestamp="2018-10-18T21:38:27"/>
	<testcase classname="decode_significant_figures_tests.TestDecodeSignificantFiguresTests" name="testDecodeSigFigWhenFiveBandsWithBlackBlackBrown" time="0.000" timestamp="2018-10-18T21:38:27"/>
	<testcase classname="decode_significant_figures_tests.TestDecodeSignificantFiguresTests" name="testDecodeSigFigWhenFourBandsWithBlackBlack" time="0.000" timestamp="2018-10-18T21:38:27"/>
	<testcase classname="decode_significant_figures_tests.TestDecodeSignificantFiguresTests" name="testDecodeSigFigWhenFourBandsWithBlackBrown" time="0.000" timestamp="2018-10-18T21:38:27"/>
	<testcase classname="decode_significant_figures_tests.TestDecodeSignificantFiguresTests" name="testDecodeSigFigWhenFourBandsWithBlackRed" time="0.000" timestamp="2018-10-18T21:38:27"/>
	<testcase classname="decode_significant_figures_tests.TestDecodeSignificantFiguresTests" name="testDecodeSigFigWhenFiveBandsWithBlackBlackRed" time="0.001" timestamp="2018-10-18T21:38:27">
		<failure message="21 != 2" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/Users/ras/Projects/Python/cs3280/project2/src/unittest/python/decode_significant_figures_tests.py", line 29, in testDecodeSigFigWhenFiveBandsWithBlackBlackRed
    self.assertEquals(decodeSignificantFigures(colors), 2)
AssertionError: 21 != 2
]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
