<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="validate_colors_list_tests.TestValidateColorsList-20181017210344" skipped="0" tests="1" time="0.001" timestamp="2018-10-17T21:03:44">
	<testcase classname="validate_colors_list_tests.TestValidateColorsList" name="testValidateColorsListWhenColorsListIsNone" time="0.001" timestamp="2018-10-17T21:03:44">
		<error message="Colors list cannot be None." type="ValueError">
<![CDATA[Traceback (most recent call last):
  File "/Users/ras/Projects/Python/cs3280/project2/src/unittest/python/validate_colors_list_tests.py", line 8, in testValidateColorsListWhenColorsListIsNone
    self.assertRaises(ValueError, validateColorsList(None))
  File "/Users/ras/Projects/Python/cs3280/project2/src/main/python/resistor.py", line 12, in validateColorsList
    raise ValueError("Colors list cannot be None.")
ValueError: Colors list cannot be None.
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
