<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="validate_colors_list_tests.TestValidateColorsList-20181017211007" skipped="0" tests="3" time="0.001" timestamp="2018-10-17T21:10:07">
	<testcase classname="validate_colors_list_tests.TestValidateColorsList" name="testValidateColorsListWhenColorsListIsEmpty" time="0.000" timestamp="2018-10-17T21:10:07"/>
	<testcase classname="validate_colors_list_tests.TestValidateColorsList" name="testValidateColorsListWhenColorsListIsNone" time="0.000" timestamp="2018-10-17T21:10:07"/>
	<testcase classname="validate_colors_list_tests.TestValidateColorsList" name="testValidateColorsListWhenColorsListContainsOneColor" time="0.001" timestamp="2018-10-17T21:10:07">
		<failure message="ValueError not raised by validateColorsList" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/Users/ras/Projects/Python/cs3280/project2/src/unittest/python/validate_colors_list_tests.py", line 17, in testValidateColorsListWhenColorsListContainsOneColor
    self.assertRaises(ValueError, validateColorsList, colors)
AssertionError: ValueError not raised by validateColorsList
]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
